logging:
  level:
    ROOT: INFO
spring:
  datasource:
    #url: jdbc:h2:mem:bil0104
    url: jdbc:h2:file:./edison
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  messages:
    basename: messages
  thymeleaf:
    cache: false
    cacheable: false
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
  h2:
    console:
      enabled: true
server:
  port: 8082